DROP VIEW IF EXISTS public.hs_edumate_contacts_master_view CASCADE;

CREATE VIEW public.hs_edumate_contacts_master_view AS
SELECT
  c.id AS contact_id,
  c.hs_object_id,
  c.b2b_partner_id,
  c.hs_created_by_user_id,
  c.hs_createdate,
  c.hs_lastmodifieddate,
  c.hs_updated_by_user_id,
  c.hubspot_owner_id,
  c.base_currency,
  c.study_destination_currency,
  c.user_selected_currency,
  c.course_type,
  c.co_applicant_1_email,
  c.co_applicant_1_mobile_number,
  c.is_deleted,
  c.created_at,
  c.updated_at,
  pi.first_name,
  pi.last_name,
  pi.email,
  pi.phone_number,
  pi.date_of_birth,
  pi.gender,
  pi.nationality,
  pi.current_address,
  pi.citycurrent_address,
  pi.state_current_address,
  pi.country_current_address,
  pi.pincode_current_address,
  pi.permanent_address,
  pi.city_permanent_address,
  pi.state_permanent_address,
  pi.country_permanent_address,
  pi.pincode_permanent_address,
  ap.admission_status,
  ap.current_education_level,
  ap.current_institution,
  ap.current_course_major,
  ap.current_cgpa_percentage,
  ap.current_graduation_year,
  ap.course_duration_months,
  ap.cat_score,
  ap.gre_score,
  ap.gmat_score,
  ap.toefl_score,
  ap.ielts_score,
  ap.sat_score,
  ap.duolingo_score,
  ap.nmat_score,
  ap.xat_score,
  ap.other_test_scores,
  ap.target_degree_level,
  ap.target_course_major,
  ap.preferred_study_destination,
  ap.target_universities,
  ap.intended_start_term,
  ap.intended_start_date,
  ap.intake_month,
  ap.intake_year,
  aj.assigned_counselor,
  aj.counselor_notes,
  aj.current_status_disposition,
  aj.current_status_disposition_reason,
  aj.priority_level,
  aj.first_contact_date,
  aj.last_contact_date,
  aj.follow_up_date,
  aj.next_follow_up_date,
  fi.annual_family_income,
  fi.currency,
  fi.co_applicant_1_name,
  fi.co_applicant_1_income,
  fi.co_applicant_1_occupation,
  fi.co_applicant_1_relationship,
  fi.co_applicant_2_name,
  fi.co_applicant_2_income,
  fi.co_applicant_2_occupation,
  fi.co_applicant_2_relationship,
  fi.co_applicant_3_name,
  fi.co_applicant_3_income,
  fi.co_applicant_3_occupation,
  fi.co_applicant_3_relationship,
  fi.collateral_available,
  fi.collateral_type,
  fi.collateral_value,
  fi.collateral_2_available,
  fi.collateral_2_type,
  fi.collateral_2_value,
  fi.living_expenses,
  fi.other_expenses,
  fi.total_course_cost,
  fi.tuition_fee,
  fi.loan_amount_required,
  fi.scholarship_amount,
  fi.self_funding_amount,
  la.lead_source,
  la.lead_source_detail,
  la.lead_quality_score,
  la.lead_reference_code,
  la.b2b_partner_name,
  la.partner_commission_applicable,
  la.referral_person_name,
  la.referral_person_contact,
  la.utm_source,
  la.utm_medium,
  la.utm_campaign,
  la.utm_term,
  la.utm_content,
  lp.loan_type_preference,
  lp.repayment_type_preference,
  st.created_by,
  st.created_date,
  st.last_modified_by,
  st.last_modified_date,
  st.data_source,
  st.student_record_status,
  st.tags,
  st.gdpr_consent,
  st.marketing_consent
FROM public.hs_edumate_contacts c
LEFT JOIN public.hs_edumate_contacts_personal_information pi ON c.id = pi.contact_id
LEFT JOIN public.hs_edumate_contacts_academic_profiles ap ON c.id = ap.contact_id
LEFT JOIN public.hs_edumate_contacts_application_journey aj ON c.id = aj.contact_id
LEFT JOIN public.hs_edumate_contacts_financial_info fi ON c.id = fi.contact_id
LEFT JOIN public.hs_edumate_contacts_lead_attribution la ON c.id = la.contact_id
LEFT JOIN public.hs_edumate_contacts_loan_preferences lp ON c.id = lp.contact_id
LEFT JOIN public.hs_edumate_contacts_system_tracking st ON c.id = st.contact_id
WHERE c.is_deleted = FALSE;