import { config } from "dotenv";
config();

export const {
  PORT,
  NODE_ENV,
  LOG_LEVEL,
  LOG_MAX_FILES,
  LOG_MAX_SIZE,
  JWT_SECRET,
  FRONTEND_URL,
  HUBSPOT_ACCESS_TOKEN,
  HUBSPOT_BASE_URL,
  HUBSPOT_EDUMATE_CONTACT_OBJECT_TYPE,
  IP_API_BASE_URL,
  IP_API_KEY,
  EMAIL_USER,
  EMAIL_PASS,
  DEFAULT_FROM_EMAIL,
  CONTACT_TEAM_URL,
  CHECK_ELIGIBILITY_URL,
  SMTP_HOST,
  SMTP_PORT,
  HUBSPOT_B2B_PARTNERS_OBJECT_TYPE,
  API_KEY,
  HUBSPOT_LOAN_APPLICATIONS_OBJECT_TYPE,
  EXCHANGE_RATE_API_KEY,
} = process.env;